[general]
import = [
  "~/.config/alacritty/keybind.toml",
  "~/.config/alacritty/nord.toml",
]


[cursor]
style = "Block"
unfocused_hollow = true

[debug]
persistent_logging = false
render_timer = false

[env]
COLORTERM = "truecolor"
TERM = "xterm-256color"

[font]

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.normal]
style = "Light"
# style = "Regular"
family = "FiraCode Nerd Font Mono"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true

[window.padding]
x = 0
y = 0

[keyboard]

